name: women_safety_app # Replace with your actual package name if different
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Permissions & Background Tasks
  sms_sender_background: ^1.0.7
  permission_handler: ^11.3.1

  # Firebase Core & Auth
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2

  # Firestore (For Profiles & Local Path Records)
  cloud_firestore: ^5.6.5

  # Media & File System
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Preferences & App Assets
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

  # ML Kit & Maps
  google_mlkit_text_recognition: ^0.16.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^14.0.3
  google_maps_flutter: ^2.18.0
  geocoding: ^5.0.0
  sidebarx: ^0.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png