// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAQCEE2wT0Zw4hFMECCO5azfMp2uiXN0',
    appId: '1:727112444278:web:4f39b6f653a5928a5f7257',
    messagingSenderId: '727112444278',
    projectId: 'device-streaming-03cc2fae',
    authDomain: 'device-streaming-03cc2fae.firebaseapp.com',
    storageBucket: 'device-streaming-03cc2fae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0XHycY2O9ExpGBFOP7vO7knBnhVBzUQ',
    appId: '1:727112444278:android:7b2771d70f3bcdb25f7257',
    messagingSenderId: '727112444278',
    projectId: 'device-streaming-03cc2fae',
    storageBucket: 'device-streaming-03cc2fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbL2CGFe6ZvNTNXh2v0JDYaCmaOgUg8Q',
    appId: '1:727112444278:ios:d80d6d22931beaf65f7257',
    messagingSenderId: '727112444278',
    projectId: 'device-streaming-03cc2fae',
    storageBucket: 'device-streaming-03cc2fae.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbL2CGFe6ZvNTNXh2v0JDYaCmaOgUg8Q',
    appId: '1:727112444278:ios:d80d6d22931beaf65f7257',
    messagingSenderId: '727112444278',
    projectId: 'device-streaming-03cc2fae',
    storageBucket: 'device-streaming-03cc2fae.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkAQCEE2wT0Zw4hFMECCO5azfMp2uiXN0',
    appId: '1:727112444278:web:0ba4dbed70e602cf5f7257',
    messagingSenderId: '727112444278',
    projectId: 'device-streaming-03cc2fae',
    authDomain: 'device-streaming-03cc2fae.firebaseapp.com',
    storageBucket: 'device-streaming-03cc2fae.firebasestorage.app',
  );
}
